// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: book.proto

package com.apilot.lottoapiserver.protobuf.book;

public class Book {
  public Book() {}
  
  public String defToStr(){
    return "def to str";
  }

}
