// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: book.proto

package com.apilot.lottoapiserver.protobuf.book;

public final class Book {
  private Book() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_apilotto_book_BookProduct_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_apilotto_book_BookProduct_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nbook.proto\022\rapilotto_book\"_\n\013BookProdu" +
      "ct\022\013\n\003sku\030\001 \001(\003\022\021\n\tproductId\030\002 \001(\003\022\020\n\010pr" +
      "odname\030\003 \001(\t\022\r\n\005value\030\004 \001(\t\022\017\n\007enabled\030\005" +
      " \001(\0102\r\n\013BookServiceB1\n\'com.apilot.lottoa" +
      "piserver.protobuf.bookP\001Z\004/apib\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_apilotto_book_BookProduct_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_apilotto_book_BookProduct_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_apilotto_book_BookProduct_descriptor,
        new java.lang.String[] { "Sku", "ProductId", "Prodname", "Value", "Enabled", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
