// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: book.proto

package com.apilot.lottoapiserver.protobuf.book;

public interface BookProductOrBuilder extends
    // @@protoc_insertion_point(interface_extends:apilotto_book.BookProduct)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 sku = 1;</code>
   * @return The sku.
   */
  long getSku();

  /**
   * <code>int64 productId = 2;</code>
   * @return The productId.
   */
  long getProductId();

  /**
   * <code>string prodname = 3;</code>
   * @return The prodname.
   */
  java.lang.String getProdname();
  /**
   * <code>string prodname = 3;</code>
   * @return The bytes for prodname.
   */
  com.google.protobuf.ByteString
      getProdnameBytes();

  /**
   * <code>string value = 4;</code>
   * @return The value.
   */
  java.lang.String getValue();
  /**
   * <code>string value = 4;</code>
   * @return The bytes for value.
   */
  com.google.protobuf.ByteString
      getValueBytes();

  /**
   * <code>bool enabled = 5;</code>
   * @return The enabled.
   */
  boolean getEnabled();
}
