// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: book.proto

package com.apilot.lottoapiserver.protobuf.book;

/**
 * Protobuf type {@code apilotto_book.BookProduct}
 */
public final class BookProduct extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:apilotto_book.BookProduct)
    BookProductOrBuilder {
private static final long serialVersionUID = 0L;
  // Use BookProduct.newBuilder() to construct.
  private BookProduct(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private BookProduct() {
    prodname_ = "";
    value_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new BookProduct();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private BookProduct(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            sku_ = input.readInt64();
            break;
          }
          case 16: {

            productId_ = input.readInt64();
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            prodname_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            value_ = s;
            break;
          }
          case 40: {

            enabled_ = input.readBool();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (com.google.protobuf.UninitializedMessageException e) {
      throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.apilot.lottoapiserver.protobuf.book.Book.internal_static_apilotto_book_BookProduct_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.apilot.lottoapiserver.protobuf.book.Book.internal_static_apilotto_book_BookProduct_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.apilot.lottoapiserver.protobuf.book.BookProduct.class, com.apilot.lottoapiserver.protobuf.book.BookProduct.Builder.class);
  }

  public static final int SKU_FIELD_NUMBER = 1;
  private long sku_;
  /**
   * <code>int64 sku = 1;</code>
   * @return The sku.
   */
  @java.lang.Override
  public long getSku() {
    return sku_;
  }

  public static final int PRODUCTID_FIELD_NUMBER = 2;
  private long productId_;
  /**
   * <code>int64 productId = 2;</code>
   * @return The productId.
   */
  @java.lang.Override
  public long getProductId() {
    return productId_;
  }

  public static final int PRODNAME_FIELD_NUMBER = 3;
  private volatile java.lang.Object prodname_;
  /**
   * <code>string prodname = 3;</code>
   * @return The prodname.
   */
  @java.lang.Override
  public java.lang.String getProdname() {
    java.lang.Object ref = prodname_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      prodname_ = s;
      return s;
    }
  }
  /**
   * <code>string prodname = 3;</code>
   * @return The bytes for prodname.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getProdnameBytes() {
    java.lang.Object ref = prodname_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      prodname_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int VALUE_FIELD_NUMBER = 4;
  private volatile java.lang.Object value_;
  /**
   * <code>string value = 4;</code>
   * @return The value.
   */
  @java.lang.Override
  public java.lang.String getValue() {
    java.lang.Object ref = value_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      value_ = s;
      return s;
    }
  }
  /**
   * <code>string value = 4;</code>
   * @return The bytes for value.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getValueBytes() {
    java.lang.Object ref = value_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      value_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ENABLED_FIELD_NUMBER = 5;
  private boolean enabled_;
  /**
   * <code>bool enabled = 5;</code>
   * @return The enabled.
   */
  @java.lang.Override
  public boolean getEnabled() {
    return enabled_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (sku_ != 0L) {
      output.writeInt64(1, sku_);
    }
    if (productId_ != 0L) {
      output.writeInt64(2, productId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(prodname_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, prodname_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(value_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, value_);
    }
    if (enabled_ != false) {
      output.writeBool(5, enabled_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (sku_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, sku_);
    }
    if (productId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, productId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(prodname_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, prodname_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(value_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, value_);
    }
    if (enabled_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(5, enabled_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.apilot.lottoapiserver.protobuf.book.BookProduct)) {
      return super.equals(obj);
    }
    com.apilot.lottoapiserver.protobuf.book.BookProduct other = (com.apilot.lottoapiserver.protobuf.book.BookProduct) obj;

    if (getSku()
        != other.getSku()) return false;
    if (getProductId()
        != other.getProductId()) return false;
    if (!getProdname()
        .equals(other.getProdname())) return false;
    if (!getValue()
        .equals(other.getValue())) return false;
    if (getEnabled()
        != other.getEnabled()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SKU_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getSku());
    hash = (37 * hash) + PRODUCTID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getProductId());
    hash = (37 * hash) + PRODNAME_FIELD_NUMBER;
    hash = (53 * hash) + getProdname().hashCode();
    hash = (37 * hash) + VALUE_FIELD_NUMBER;
    hash = (53 * hash) + getValue().hashCode();
    hash = (37 * hash) + ENABLED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getEnabled());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.apilot.lottoapiserver.protobuf.book.BookProduct parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.apilot.lottoapiserver.protobuf.book.BookProduct parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.apilot.lottoapiserver.protobuf.book.BookProduct parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.apilot.lottoapiserver.protobuf.book.BookProduct parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.apilot.lottoapiserver.protobuf.book.BookProduct parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.apilot.lottoapiserver.protobuf.book.BookProduct parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.apilot.lottoapiserver.protobuf.book.BookProduct parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.apilot.lottoapiserver.protobuf.book.BookProduct parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.apilot.lottoapiserver.protobuf.book.BookProduct parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.apilot.lottoapiserver.protobuf.book.BookProduct parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.apilot.lottoapiserver.protobuf.book.BookProduct parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.apilot.lottoapiserver.protobuf.book.BookProduct parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.apilot.lottoapiserver.protobuf.book.BookProduct prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code apilotto_book.BookProduct}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:apilotto_book.BookProduct)
      com.apilot.lottoapiserver.protobuf.book.BookProductOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.apilot.lottoapiserver.protobuf.book.Book.internal_static_apilotto_book_BookProduct_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.apilot.lottoapiserver.protobuf.book.Book.internal_static_apilotto_book_BookProduct_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.apilot.lottoapiserver.protobuf.book.BookProduct.class, com.apilot.lottoapiserver.protobuf.book.BookProduct.Builder.class);
    }

    // Construct using com.apilot.lottoapiserver.protobuf.book.BookProduct.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      sku_ = 0L;

      productId_ = 0L;

      prodname_ = "";

      value_ = "";

      enabled_ = false;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.apilot.lottoapiserver.protobuf.book.Book.internal_static_apilotto_book_BookProduct_descriptor;
    }

    @java.lang.Override
    public com.apilot.lottoapiserver.protobuf.book.BookProduct getDefaultInstanceForType() {
      return com.apilot.lottoapiserver.protobuf.book.BookProduct.getDefaultInstance();
    }

    @java.lang.Override
    public com.apilot.lottoapiserver.protobuf.book.BookProduct build() {
      com.apilot.lottoapiserver.protobuf.book.BookProduct result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.apilot.lottoapiserver.protobuf.book.BookProduct buildPartial() {
      com.apilot.lottoapiserver.protobuf.book.BookProduct result = new com.apilot.lottoapiserver.protobuf.book.BookProduct(this);
      result.sku_ = sku_;
      result.productId_ = productId_;
      result.prodname_ = prodname_;
      result.value_ = value_;
      result.enabled_ = enabled_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.apilot.lottoapiserver.protobuf.book.BookProduct) {
        return mergeFrom((com.apilot.lottoapiserver.protobuf.book.BookProduct)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.apilot.lottoapiserver.protobuf.book.BookProduct other) {
      if (other == com.apilot.lottoapiserver.protobuf.book.BookProduct.getDefaultInstance()) return this;
      if (other.getSku() != 0L) {
        setSku(other.getSku());
      }
      if (other.getProductId() != 0L) {
        setProductId(other.getProductId());
      }
      if (!other.getProdname().isEmpty()) {
        prodname_ = other.prodname_;
        onChanged();
      }
      if (!other.getValue().isEmpty()) {
        value_ = other.value_;
        onChanged();
      }
      if (other.getEnabled() != false) {
        setEnabled(other.getEnabled());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.apilot.lottoapiserver.protobuf.book.BookProduct parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.apilot.lottoapiserver.protobuf.book.BookProduct) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private long sku_ ;
    /**
     * <code>int64 sku = 1;</code>
     * @return The sku.
     */
    @java.lang.Override
    public long getSku() {
      return sku_;
    }
    /**
     * <code>int64 sku = 1;</code>
     * @param value The sku to set.
     * @return This builder for chaining.
     */
    public Builder setSku(long value) {
      
      sku_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 sku = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearSku() {
      
      sku_ = 0L;
      onChanged();
      return this;
    }

    private long productId_ ;
    /**
     * <code>int64 productId = 2;</code>
     * @return The productId.
     */
    @java.lang.Override
    public long getProductId() {
      return productId_;
    }
    /**
     * <code>int64 productId = 2;</code>
     * @param value The productId to set.
     * @return This builder for chaining.
     */
    public Builder setProductId(long value) {
      
      productId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 productId = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearProductId() {
      
      productId_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object prodname_ = "";
    /**
     * <code>string prodname = 3;</code>
     * @return The prodname.
     */
    public java.lang.String getProdname() {
      java.lang.Object ref = prodname_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        prodname_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string prodname = 3;</code>
     * @return The bytes for prodname.
     */
    public com.google.protobuf.ByteString
        getProdnameBytes() {
      java.lang.Object ref = prodname_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        prodname_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string prodname = 3;</code>
     * @param value The prodname to set.
     * @return This builder for chaining.
     */
    public Builder setProdname(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      prodname_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string prodname = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearProdname() {
      
      prodname_ = getDefaultInstance().getProdname();
      onChanged();
      return this;
    }
    /**
     * <code>string prodname = 3;</code>
     * @param value The bytes for prodname to set.
     * @return This builder for chaining.
     */
    public Builder setProdnameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      prodname_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object value_ = "";
    /**
     * <code>string value = 4;</code>
     * @return The value.
     */
    public java.lang.String getValue() {
      java.lang.Object ref = value_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        value_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string value = 4;</code>
     * @return The bytes for value.
     */
    public com.google.protobuf.ByteString
        getValueBytes() {
      java.lang.Object ref = value_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        value_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string value = 4;</code>
     * @param value The value to set.
     * @return This builder for chaining.
     */
    public Builder setValue(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      value_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string value = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearValue() {
      
      value_ = getDefaultInstance().getValue();
      onChanged();
      return this;
    }
    /**
     * <code>string value = 4;</code>
     * @param value The bytes for value to set.
     * @return This builder for chaining.
     */
    public Builder setValueBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      value_ = value;
      onChanged();
      return this;
    }

    private boolean enabled_ ;
    /**
     * <code>bool enabled = 5;</code>
     * @return The enabled.
     */
    @java.lang.Override
    public boolean getEnabled() {
      return enabled_;
    }
    /**
     * <code>bool enabled = 5;</code>
     * @param value The enabled to set.
     * @return This builder for chaining.
     */
    public Builder setEnabled(boolean value) {
      
      enabled_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool enabled = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearEnabled() {
      
      enabled_ = false;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:apilotto_book.BookProduct)
  }

  // @@protoc_insertion_point(class_scope:apilotto_book.BookProduct)
  private static final com.apilot.lottoapiserver.protobuf.book.BookProduct DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.apilot.lottoapiserver.protobuf.book.BookProduct();
  }

  public static com.apilot.lottoapiserver.protobuf.book.BookProduct getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<BookProduct>
      PARSER = new com.google.protobuf.AbstractParser<BookProduct>() {
    @java.lang.Override
    public BookProduct parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new BookProduct(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<BookProduct> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<BookProduct> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.apilot.lottoapiserver.protobuf.book.BookProduct getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

