// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sample.proto

package com.apilot.lottoapiserver.protobuf.sample;

public final class Sample {
  private Sample() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_apilotto_sample_SampleProduct_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_apilotto_sample_SampleProduct_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014sample.proto\022\017apilotto_sample\"a\n\rSampl" +
      "eProduct\022\013\n\003sku\030\001 \001(\003\022\021\n\tproductId\030\002 \001(\003" +
      "\022\020\n\010prodname\030\003 \001(\t\022\r\n\005value\030\004 \001(\t\022\017\n\007ena" +
      "bled\030\005 \001(\0102\017\n\rSampleServiceB3\n)com.apilo" +
      "t.lottoapiserver.protobuf.sampleP\001Z\004/api" +
      "b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_apilotto_sample_SampleProduct_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_apilotto_sample_SampleProduct_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_apilotto_sample_SampleProduct_descriptor,
        new java.lang.String[] { "Sku", "ProductId", "Prodname", "Value", "Enabled", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
