// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sample.proto

package com.apilot.lottoapiserver.protobuf.sample;

public class Sample {
  public Sample() {}
  
  public String getVal(){
    return "get val";
  }
}
