// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v3.21.0
// source: sample.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SampleProduct struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sku           int64                  `protobuf:"varint,1,opt,name=sku,proto3" json:"sku,omitempty"`
	ProductId     int64                  `protobuf:"varint,2,opt,name=productId,proto3" json:"productId,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Value         string                 `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	Enabled       bool                   `protobuf:"varint,5,opt,name=enabled,proto3" json:"enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SampleProduct) Reset() {
	*x = SampleProduct{}
	mi := &file_sample_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SampleProduct) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SampleProduct) ProtoMessage() {}

func (x *SampleProduct) ProtoReflect() protoreflect.Message {
	mi := &file_sample_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SampleProduct.ProtoReflect.Descriptor instead.
func (*SampleProduct) Descriptor() ([]byte, []int) {
	return file_sample_proto_rawDescGZIP(), []int{0}
}

func (x *SampleProduct) GetSku() int64 {
	if x != nil {
		return x.Sku
	}
	return 0
}

func (x *SampleProduct) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *SampleProduct) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SampleProduct) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *SampleProduct) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

var File_sample_proto protoreflect.FileDescriptor

const file_sample_proto_rawDesc = "" +
	"\n" +
	"\fsample.proto\x12\x0fapilotto_sample\"\x83\x01\n" +
	"\rSampleProduct\x12\x10\n" +
	"\x03sku\x18\x01 \x01(\x03R\x03sku\x12\x1c\n" +
	"\tproductId\x18\x02 \x01(\x03R\tproductId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x04 \x01(\tR\x05value\x12\x18\n" +
	"\aenabled\x18\x05 \x01(\bR\aenabled2\x0f\n" +
	"\rSampleServiceBL\n" +
	")com.apilot.lottoapiserver.protobuf.sampleP\x01Z\x1daplilotto/apilotto_sample;apib\x06proto3"

var (
	file_sample_proto_rawDescOnce sync.Once
	file_sample_proto_rawDescData []byte
)

func file_sample_proto_rawDescGZIP() []byte {
	file_sample_proto_rawDescOnce.Do(func() {
		file_sample_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sample_proto_rawDesc), len(file_sample_proto_rawDesc)))
	})
	return file_sample_proto_rawDescData
}

var file_sample_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_sample_proto_goTypes = []any{
	(*SampleProduct)(nil), // 0: apilotto_sample.SampleProduct
}
var file_sample_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_sample_proto_init() }
func file_sample_proto_init() {
	if File_sample_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sample_proto_rawDesc), len(file_sample_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sample_proto_goTypes,
		DependencyIndexes: file_sample_proto_depIdxs,
		MessageInfos:      file_sample_proto_msgTypes,
	}.Build()
	File_sample_proto = out.File
	file_sample_proto_goTypes = nil
	file_sample_proto_depIdxs = nil
}
